server:
  port: 5000

spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/bankAccount?authSource=admin
  kafka:
    producer:
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer